apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-data
spec:
  storageClassName: manual #Tipo de almacenamiento, manual, dinamica
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /run/desktop/mnt/host/c/Users/fmacedoniom/git/cursomicroservicios2021/ProyectoServicios/kubernetesdata/
    