#Application Name
spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    #telling the server not to register himself in the service registry
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://10.100.100.10:8761/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync